SweetSavoryTreats/Models/Flavor.cs
using System.Collections.Generic;

namespace SweetSavoryTreats.Models
{
  public class Flavor
  {
    public Flavor()
    {
      this.JoinEntities = new HashSet<FlavorTreat> ();
    }

    public int FlavorId { get; set; }
    public string Name { get; set; }
    public virtual ApplicationUser User { get; set; }
    public virtual ICollection<FlavorTreat> JoinEntities { get; set; }
  }
}

SweetSavoryTreats/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using SweetSavoryTreats.Models;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;


namespace SweetSavoryTreats.Controllers
{
  public class FlavorsController : Controller
  {
    private readonly SweetSavoryTreatsContext _db;
    private readonly UserManager<ApplicationUser> _userManager;
    public FlavorsController(UserManager<ApplicationUser> userManager, SweetSavoryTreatsContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Flavors.ToList());
    }

    [Authorize]
    public ActionResult Create()
    {
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Flavor flavor, int treatId)
    {
      _db.Flavors.Add(flavor);
      _db.SaveChanges();
      if (treatId != 0)
      {
        _db.FlavorTreats.Add(new FlavorTreat() { FlavorId = flavor.FlavorId, TreatId = treatId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisFlavor = _db.Flavors
          .Include(flavor => flavor.JoinEntities)
          .ThenInclude(join => join.Treat)
          .FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [Authorize]
    public ActionResult Edit(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Name");
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult Edit(Flavor flavor, int treatId)
    {
      if (treatId != 0)
      {
        _db.FlavorTreats.Add(new FlavorTreat() { FlavorId = flavor.FlavorId, TreatId = treatId });
      }
      _db.Entry(flavor).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize]
    public ActionResult AddTreat(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Name");
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult AddTreat(Flavor flavor, int treatId)
    {
      if (treatId != 0)
      {
      _db.FlavorTreats.Add(new FlavorTreat() { FlavorId = flavor.FlavorId, TreatId = treatId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize]
    public ActionResult Delete(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      _db.Flavors.Remove(thisFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteTreat(int joinId)
    {
      var joinEntry = _db.FlavorTreats.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreats.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

SweetSavoryTreats/Views/Flavors/AddTreat.cshtml
@{
  Layout = "_Layout";
}

@model SweetSavoryTreats.Models.Flavor

<h2>Add a Treat</h2>

<h4>Add a treat to this flavor: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.FlavorId)

  @Html.Label("Select a Treat")
  @Html.DropDownList("TreatId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Show all Flavors", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

SweetSavoryTreats/Views/Flavors/Create.cshtml
@{
  Layout = "_Layout";
}

@model SweetSavoryTreats.Models.Flavor

<h4>Add a new FLavor</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  @Html.Label("Select a Treat")
  @Html.DropDownList("TreatId")

  <input type="submit" value="Add new Flavor" class="btn btn-default" />
}

<p>@Html.ActionLink("Show all Flavors", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

SweetSavoryTreats/Views/Flavors/Delete.cshtml
@{
  Layout = "_Layout";
}

@model SweetSavoryTreats.Models.Flavor

<h2>Are you sure you want to delete this flavor: @Html.DisplayFor(model => model.Name)?</h2>
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

<p>@Html.ActionLink("Back to all Flavors", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

SweetSavoryTreats/Views/Flavors/Details.cshtml
@{
  Layout = "_Layout";
}

@model SweetSavoryTreats.Models.Flavor

<h2>Flavor Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>No available Treat(s) with this flavor.</p>
}
else
{
  <h4>All Treat(s): </h4>
  <ul>
  @foreach(var join in Model.JoinEntities)
  {
    <li>@join.Treat.Name</li>
    @using (Html.BeginForm("DeleteTreat", "Flavors"))
    {
      @Html.Hidden("joinId", @join.FlavorTreatId)
      <input type="submit" value="Delete"/>
    }
  }
  </ul>
}



@if (User.Identity.IsAuthenticated)
{
  <p>@Html.ActionLink("Add a Treat", "AddTreat", new { id = Model.FlavorId })</p>
  <p>@Html.ActionLink("Edit Current Flavor", "Edit", new { id = Model.FlavorId })</p>
  <p>@Html.ActionLink("Delete Current Flavor", "Delete", new { id = Model.FlavorId })</p>
}

<p>@Html.ActionLink("Back to list", "Index")</p>

SweetSavoryTreats/Views/Flavors/Edit.cshtml
@{
  Layout = "_Layout";
}

@model SweetSavoryTreats.Models.Flavor

<h2>Edit</h2>

<h4>Edit this Flavor: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.FlavorId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  @Html.Label("Select a Treat")
  @Html.DropDownList("TreatId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to Flavors list", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

SweetSavoryTreats/Views/Flavors/Index.cshtml
@{
  Layout = "_Layout";
}

@using SweetSavoryTreats.Models;
@model IEnumerable<SweetSavoryTreats.Models.Flavor>

<h1>All Flavors:</h1>

@if (Model.Any())
{
  <ul>
    @foreach (Flavor flavor in Model)
    {
      <li>@Html.ActionLink($"{flavor.Name}", "Details", new { id = flavor.FlavorId })</li>
    }
  </ul>
} 
else
{
  <h3>No Flavor(s) Available</h3>
}

@if (User.Identity.IsAuthenticated)
{
  <p>@Html.ActionLink("Add new Flavor", "Create")</p>
}

<p>@Html.ActionLink("Home", "Index", "Home")</p>