SweetSavoryTreats/Models/Treat.cs
using System.Collections.Generic;

namespace SweetSavoryTreats.Models
{
  public class Treat
  {
    public Treat()
    {
      this.JoinEntities = new HashSet<FlavorTreat> ();
    }

    public int TreatId { get; set; }
    public string Name { get; set; }
    public virtual ApplicationUser User { get; set; }
    public virtual ICollection<FlavorTreat> JoinEntities { get; set; }
  }
}

SweetSavoryTreats/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using SweetSavoryTreats.Models;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace SweetSavoryTreats.Controllers
{
  public class TreatsController : Controller
  {
    private readonly SweetSavoryTreatsContext _db;
    private readonly UserManager<ApplicationUser> _userManager;
    public TreatsController(UserManager<ApplicationUser> userManager, SweetSavoryTreatsContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Treats.ToList());
    }

    [Authorize]
    public ActionResult Create()
    {
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Treat treat, int flavorId)
    {
      _db.Treats.Add(treat);
      _db.SaveChanges();
      if (flavorId != 0)
      {
        _db.FlavorTreats.Add(new FlavorTreat() { FlavorId = flavorId, TreatId = treat.TreatId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisTreat = _db.Treats
          .Include(treat => treat.JoinEntities)
          .ThenInclude(join => join.Flavor)
          .FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [Authorize]
    public ActionResult Edit(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Name");
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult Edit(Treat treat, int flavorId)
    {
      if (flavorId != 0)
      {
        _db.FlavorTreats.Add(new FlavorTreat() { FlavorId = flavorId, TreatId = treat.TreatId });
      }
      _db.Entry(treat).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize]
    public ActionResult AddFlavor(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Name");
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult AddFlavor(Treat treat, int flavorId)
    {
      if (flavorId != 0)
      {
      _db.FlavorTreats.Add(new FlavorTreat() { FlavorId = flavorId, TreatId = treat.TreatId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize]
    public ActionResult Delete(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      _db.Treats.Remove(thisTreat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteFlavor(int joinId)
    {
      var joinEntry = _db.FlavorTreats.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreats.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

SweetSavoryTreats/Views/Treats/AddFlavor.cshtml
@{
  Layout = "_Layout";
}

@model SweetSavoryTreats.Models.Treat

<h2>Add a Flavor</h2>

<h4>Add a flavor to this treat: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.TreatId)

  @Html.Label("Select a Flavor")
  @Html.DropDownList("FlavorId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Show all Treats", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

SweetSavoryTreats/Views/Treats/Create.cshtml
@{
  Layout = "_Layout";
}

@model SweetSavoryTreats.Models.Treat

<h4>Add a new Treat</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  @Html.Label("Select a Flavor")
  @Html.DropDownList("FlavorId")

  <input type="submit" value="Add new Treat" class="btn btn-default" />
}

<p>@Html.ActionLink("Show all Treats", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

SweetSavoryTreats/Views/Treats/Delete.cshtml
@{
  Layout = "_Layout";
}

@model SweetSavoryTreats.Models.Treat

<h2>Are you sure you want to delete this treat: @Html.DisplayFor(model => model.Name)?</h2>
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

<p>@Html.ActionLink("Back to all Treats", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

SweetSavoryTreats/Views/Treats/Details.cshtml
@{
  Layout = "_Layout";
}

@model SweetSavoryTreats.Models.Treat

<h2>Treat Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>No available Flavor(s) with this treat.</p>
}
else
{
  <h4>All Flavor(s): </h4>
  <ul>
  @foreach(var join in Model.JoinEntities)
  {
    <li>@join.Flavor.Name</li>
    @if (User.Identity.IsAuthenticated)
    {
      @using (Html.BeginForm("DeleteFlavor", "Treats"))
      {
        @Html.Hidden("joinId", @join.FlavorTreatId)
        <input type="submit" value="Delete"/>
      }
    }
  }
  </ul>
}



@if (User.Identity.IsAuthenticated)
{
  <p>@Html.ActionLink("Add a Flavor", "AddFlavor", new { id = Model.TreatId })</p>
  <p>@Html.ActionLink("Edit Current Treat", "Edit", new { id = Model.TreatId })</p>
  <p>@Html.ActionLink("Delete Current Treat", "Delete", new { id = Model.TreatId })</p>
}

<p>@Html.ActionLink("Back to list", "Index")</p>

SweetSavoryTreats/Views/Treats/Edit.cshtml
@{
  Layout = "_Layout";
}

@model SweetSavoryTreats.Models.Treat

<h2>Edit</h2>

<h4>Edit this Treat: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.TreatId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  @Html.Label("Select a Flavor")
  @Html.DropDownList("FlavorId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to Treats list", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

SweetSavoryTreats/Views/Treats/Index.cshtml
@{
  Layout = "_Layout";
}

@using SweetSavoryTreats.Models;
@model IEnumerable<SweetSavoryTreats.Models.Treat>

<h1>All Treats:</h1>

@if (Model.Any())
{
  <ul>
    @foreach (Treat treat in Model)
    {
      <li>@Html.ActionLink($"{treat.Name}", "Details", new { id = treat.TreatId })</li>
    }
  </ul>
} 
else
{
  <h3>No Treat(s) Available</h3>
}

@if (User.Identity.IsAuthenticated)
{
  <p>@Html.ActionLink("Add new Treat", "Create")</p>
}

<p>@Html.ActionLink("Home", "Index", "Home")</p>